// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaeD39vxFoq3dF9-xe2s6hP-hIs_8RjmM',
    appId: '1:789633177672:web:94ca32a4a89301a796e07d',
    messagingSenderId: '789633177672',
    projectId: 'rgb234-meeting-app',
    authDomain: 'rgb234-meeting-app.firebaseapp.com',
    storageBucket: 'rgb234-meeting-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrz5bVNjR0RPybkgT29xlU_6LJmN9-4oU',
    appId: '1:789633177672:android:970904c2d8b25da796e07d',
    messagingSenderId: '789633177672',
    projectId: 'rgb234-meeting-app',
    storageBucket: 'rgb234-meeting-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhb7REulDk6IgZx55umuiKD4eHVoqMA4A',
    appId: '1:789633177672:ios:8ba440ec6878e5b496e07d',
    messagingSenderId: '789633177672',
    projectId: 'rgb234-meeting-app',
    storageBucket: 'rgb234-meeting-app.appspot.com',
    iosBundleId: 'com.example.meetingApp',
  );
}
