// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSd--Qwb8V6BxlHBxXjFzy1bzebEBF-go',
    appId: '1:148145374031:web:ee4f37685183c9dd4d3b3a',
    messagingSenderId: '148145374031',
    projectId: 'rgb234-flutter-meeting-app',
    authDomain: 'rgb234-flutter-meeting-app.firebaseapp.com',
    storageBucket: 'rgb234-flutter-meeting-app.appspot.com',
    measurementId: 'G-J4E3ED8NYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSANLYIRqu-nfpXcRtNiTtAGSXDIXC85Y',
    appId: '1:148145374031:android:77cc6e8aed6304314d3b3a',
    messagingSenderId: '148145374031',
    projectId: 'rgb234-flutter-meeting-app',
    storageBucket: 'rgb234-flutter-meeting-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqvdLcLOdHAW5gPFt38lS9JUFLiZgA2Kw',
    appId: '1:148145374031:ios:21c5bc9ae33bc1f34d3b3a',
    messagingSenderId: '148145374031',
    projectId: 'rgb234-flutter-meeting-app',
    storageBucket: 'rgb234-flutter-meeting-app.appspot.com',
    iosBundleId: 'com.example.meetingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqvdLcLOdHAW5gPFt38lS9JUFLiZgA2Kw',
    appId: '1:148145374031:ios:7ceeb6f0624a956e4d3b3a',
    messagingSenderId: '148145374031',
    projectId: 'rgb234-flutter-meeting-app',
    storageBucket: 'rgb234-flutter-meeting-app.appspot.com',
    iosBundleId: 'com.example.meetingApp.RunnerTests',
  );
}
